name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-check:
    name: Tests and checks
    uses: daniil-berg/reusable-workflows/.github/workflows/python-test.yaml@v0.0.1
    with:
      versions: '["3.9", "3.10", "3.11"]'
      cache: pip
      cache-dependency-path: pyproject.toml
      unittest-command: 'scripts/test.sh'
      coverage-command: 'scripts/cov.sh'
      unittest-requirements: "-e '.[dev]'"
      typecheck-command: 'scripts/typecheck.sh'
      typecheck-requirements: '-Ur requirements/dev.txt'
      typecheck-all-versions: true
      lint-command: 'scripts/lint.sh'
      lint-requirements: '-Ur requirements/dev.txt'
